/*
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and valkey-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ValkeyListerExpansion allows custom methods to be added to
// ValkeyLister.
type ValkeyListerExpansion interface{}

// ValkeyNamespaceListerExpansion allows custom methods to be added to
// ValkeyNamespaceLister.
type ValkeyNamespaceListerExpansion interface{}
